[package]
description = "UI components for building fantastic desktop application by using GPUI."
edition = "2021"
name = "gpui-component"
publish = true
version = "0.1.0"
homepage = "https://github.com/longbridge/gpui-component"
license-file = "LICENSE-APACHE"
keywords = ["ui", "desktop", "application", "GPUI"]

[lib]
doctest = false

[dependencies]
gpui.workspace = true
anyhow = "1"
image = "0.25.1"
itertools = "0.13.0"
once_cell = "1.19.0"
paste = "1"
regex = "1"
resvg = { version = "0.44.0", default-features = false, features = [
  "system-fonts",
  "text",
] }
rust-embed.workspace = true
rust-i18n = "3"
serde = "1.0.203"
serde_json = "1"
smallvec = "1.13.2"
smol = "1"
unicode-segmentation = "1.12.0"
usvg = { version = "0.44.0", default-features = false, features = [
  "system-fonts",
  "text",
] }
uuid = "1.10"
wry = "0.48.0"
# Markdown Parser
markdown = "1.0.0-alpha.22"
# HTML Parser
html5ever =  "0.27"
markup5ever_rcdom = "0.3.0"
minify-html = "0.15.0"

# Calendar
chrono = "0.4.38"

[lints]
workspace = true
