import { pendingStory } from "./story.js";

export const stories = [
  pendingStory({
    id: "avatar",
    title: "Avatar",
    group: "Content",
    rustStory: "AvatarStory",
    description: "Person and group identity.",
    states: ["image", "initials", "fallback"],
    availability: "pending",
    api: "Avatar",
  }),
  pendingStory({
    id: "badge",
    title: "Badge",
    group: "Content",
    rustStory: "BadgeStory",
    description: "Compact semantic label.",
    states: ["neutral", "success", "warning", "destructive"],
    availability: "pending",
    api: "Badge",
  }),
  pendingStory({
    id: "description-list",
    title: "DescriptionList",
    group: "Content",
    rustStory: "DescriptionListStory",
    description: "Key-value metadata display.",
    states: ["stacked", "inline"],
    availability: "pending",
    api: "DescriptionList",
  }),
  pendingStory({
    id: "group-box",
    title: "GroupBox",
    group: "Content",
    rustStory: "GroupBoxStory",
    description: "Labeled content container.",
    states: ["normal", "disabled"],
    availability: "pending",
    api: "GroupBox",
  }),
  pendingStory({
    id: "progress",
    title: "Progress",
    group: "Content",
    rustStory: "ProgressStory",
    description: "Determinate and indeterminate progress.",
    states: ["0%", "50%", "complete", "loading"],
    availability: "pending",
    api: "Progress",
  }),
  pendingStory({
    id: "skeleton",
    title: "Skeleton",
    group: "Content",
    rustStory: "SkeletonStory",
    description: "Loading placeholders.",
    states: ["text", "avatar", "card"],
    availability: "pending",
    api: "Skeleton",
  }),
  pendingStory({
    id: "spinner",
    title: "Spinner",
    group: "Content",
    rustStory: "SpinnerStory",
    description: "Indeterminate loading indicator.",
    states: ["normal", "muted", "large"],
    availability: "pending",
    api: "Spinner",
  }),
  pendingStory({
    id: "tag",
    title: "Tag",
    group: "Content",
    rustStory: "TagStory",
    description: "Removable metadata token.",
    states: ["normal", "selected", "disabled"],
    availability: "pending",
    api: "Tag",
  }),
];
