// One checked relationship for every gallery route. Some inventory surfaces
// (such as Plot) share the Rust Story that owns their example.
export const coveredBy = [
  { route: "introduction", registrations: ["Link"] },
  { route: "accordion", registrations: ["Accordion"] },
  { route: "alert", registrations: ["Alert"] },
  { route: "alert-dialog", registrations: ["AlertDialog"] },
  { route: "avatar", registrations: ["Avatar"] },
  { route: "badge", registrations: ["Badge"] },
  { route: "breadcrumb", registrations: ["Breadcrumb"] },
  { route: "button", registrations: ["Button"] },
  { route: "calendar", registrations: ["Calendar"] },
  { route: "chart", registrations: ["BarChart", "Plot"] },
  { route: "checkbox", registrations: ["Checkbox"] },
  { route: "clipboard", registrations: ["Clipboard"] },
  { route: "collapsible", registrations: ["Collapsible"] },
  { route: "color-picker", registrations: ["ColorPicker"] },
  { route: "combobox", registrations: ["Combobox"] },
  { route: "command", registrations: ["Command"] },
  { route: "data-table", registrations: ["DataTable"] },
  { route: "date-picker", registrations: ["DatePicker"] },
  { route: "description-list", registrations: ["DescriptionList"] },
  { route: "dialog", registrations: ["Dialog"] },
  { route: "dock", registrations: ["Dock"] },
  { route: "dropdown-button", registrations: ["DropdownButton"] },
  { route: "editor", registrations: ["Editor", "Text"] },
  { route: "form", registrations: ["Form"] },
  { route: "group-box", registrations: ["GroupBox"] },
  { route: "hover-card", registrations: ["HoverCard"] },
  { route: "icon", registrations: ["Icon"] },
  { route: "image", registrations: ["Image"] },
  { route: "input", registrations: ["Input"] },
  { route: "kbd", registrations: ["Kbd"] },
  { route: "label", registrations: ["Label"] },
  { route: "list", registrations: ["List", "SearchableList"] },
  { route: "menu", registrations: ["Menu"] },
  { route: "native-menu", registrations: ["NativeMenuTrigger"] },
  { route: "notification", registrations: ["Notification"] },
  { route: "number-input", registrations: ["NumberInput"] },
  { route: "otp-input", registrations: ["OtpInput"] },
  { route: "pagination", registrations: ["Pagination"] },
  { route: "popover", registrations: ["Popover"] },
  { route: "progress", registrations: ["Progress"] },
  { route: "radio", registrations: ["Radio"] },
  { route: "rating", registrations: ["Rating"] },
  { route: "resizable", registrations: ["Resizable"] },
  { route: "scrollbar", registrations: ["Scrollbar", "Scroll"] },
  { route: "select", registrations: ["Select"] },
  { route: "separator", registrations: ["Separator"] },
  { route: "settings", registrations: ["Settings"] },
  { route: "shell", registrations: [] },
  { route: "sheet", registrations: ["Sheet"] },
  { route: "sidebar", registrations: ["Sidebar"] },
  { route: "skeleton", registrations: ["Skeleton"] },
  { route: "slider", registrations: ["Slider"] },
  { route: "spinner", registrations: ["Spinner"] },
  { route: "status-bar", registrations: ["StatusBar"] },
  { route: "stepper", registrations: ["Stepper"] },
  { route: "switch", registrations: ["Switch"] },
  { route: "table", registrations: ["Table"] },
  { route: "tabs", registrations: ["Tabs", "Tab"] },
  { route: "tag", registrations: ["Tag"] },
  { route: "textarea", registrations: ["Textarea"] },
  { route: "theme-colors", registrations: [] },
  { route: "toggle", registrations: ["Toggle"] },
  { route: "tooltip", registrations: ["Tooltip"] },
  { route: "tree", registrations: ["Tree"] },
  { route: "virtual-list", registrations: ["VirtualList"] },
];

/** @param {string} route */
export function coveredSurfaces(route) {
  return coveredBy.find((entry) => entry.route === route)?.registrations ?? [];
}
