[package]
name = "generate-theme-schema"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json.workspace = true
gpui-component.workspace = true
schemars.workspace = true

[lints]
workspace = true
