name: CI
on:
  pull_request:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  test:
    name: Test
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
            run_on: macos-latest
          - target: x86_64-linux-gnu
            run_on: ubuntu-latest
          - target: x86_64-windows-msvc
            run_on: windows-latest
    runs-on: ${{ matrix.run_on }}
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        if: ${{ matrix.run_on != 'windows-latest' }}
        run: script/bootstrap
      - name: Machete
        if: ${{ matrix.run_on == 'macos-latest' }}
        uses: bnjbvr/cargo-machete@main
      - name: Setup | Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: test-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Typo check
        if: ${{ matrix.run_on == 'macos-latest' }}
        run: |
          cargo install typos-cli || echo "typos-cli already installed"
          typos
      - name: Lint
        if: ${{ matrix.run_on == 'macos-latest' }}
        run: |
          cargo clippy -- --deny warnings
      - name: Build test
        run: |
          cargo test --all
