name: "Release Crate"
on:
  push:
    tags:
      - "v*"
jobs:
  publish_crate:
    name: Publish Crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/cargo@v1
        if: startsWith(github.ref, 'refs/tags/v')
        name: Release Crate
        with:
          command: publish
          args: --workspace --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
